### ISSUE TITLE
Alguém sabe dizer o que deu aqui?

### ISSUE THREAD

**Issue by CentroEducacional-CEC** [caioagiani/blaze-bot#3]
Microsoft Windows [versão 10.0.19044.2130]
(c) Microsoft Corporation. Todos os direitos reservados.

C:\Users\SERVIDOR\Desktop\Bots\blaze-bot-main>npm install
npm WARN deprecated @types/axios@0.14.0: This is a stub types definition for axios (https://github.com/mzabriskie/axios). axios provides its own type definitions, so you don't need @types/axios installed!
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated eslint-loader@4.0.2: This loader has been deprecated. Please use eslint-webpack-plugin
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 432 packages, and audited 433 packages in 36s

54 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

C:\Users\SERVIDOR\Desktop\Bots\blaze-bot-main>npm run dev

> blaze-bot@0.5.0 dev
> ts-node-dev --respawn --transpile-only --ignore-watch node_modules --ignore-watch src/data -r dotenv/config src/index.ts

[INFO] Invalid Date ts-node-dev ver. 1.1.7 (using ts-node ver. 9.1.1, typescript ver. 4.3.4)
SERVER: ON
MongooseError: Operation `doubles.findOneAndUpdate()` buffering timed out after 10000ms
    at Timeout.<anonymous> (C:\Users\SERVIDOR\Desktop\Bots\blaze-bot-main\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:198:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[ERROR] Invalid Date MongooseError: Operation `doubles.findOneAndUpdate()` buffering timed out after 10000ms

**Comment by caioagiani** [comment]
Você precisa criar a .env e ter um acesso ao banco de dados MongoDB (localmente ou algum cluster).

```sh
# Baixar projeto
$ git clone git@github.com:caioagiani/blaze-bot.git

# Configurar .env
$ cp .env.example .env

# Instalar dependências
$ yarn install ou npm install

# Iniciar aplicação
$ yarn dev ou npm run dev
```
